export const CONSTANTS = {
  APP_NAME: 'Spendly AI',
  SUPPORTED_CURRENCIES: ['THB', 'USD', 'EUR', 'GBP', 'JPY'],
  DEFAULT_CURRENCY: 'THB',
  DEFAULT_LOCALE: 'th-TH',
  RECEIPT_IMAGE_MAX_WIDTH: 1200,
  RECEIPT_IMAGE_COMPRESSION: 0.7,
  PAGINATION_LIMIT: 20,
};
